[package]
name = "ffq-execution"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
vector = []

[dependencies]
ffq-common = { path = "../common" }
arrow.workspace = true
futures.workspace = true
tracing.workspace = true
serde.workspace = true
